# File: _config.yml
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
    defaults:
      -
        scope:
          path: ""
          type: "posts"
        values:
          layout: "my-site"
      -
        scope:
          path: "projects"
          type: "pages" # previously `page` in Jekyll 2.2.
        values:
          layout: "project" # overrides previous default layout
          author: "Mr. Hyde"